name: locode
description: "Locode: Gemini 3 Hackathon Edition - Professional Security Scanner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Architecture
  get_it: ^8.0.0
  flutter_bloc: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # AI
  google_generative_ai: ^0.4.7
  
  # Networking
  http: ^1.2.2
  internet_connection_checker: ^3.0.1
  
  # Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  
  # Backend
  supabase: ^2.0.0
  
  # Maps
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  
  # Browser
  webview_flutter: ^4.10.0
  
  # UI & Motion
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  
  # Deep Linking
  
  # Icons
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.0
  flutter_local_notifications: ^17.0.0
  flutter_compass: ^0.8.0
  flutter_svg: ^2.0.10+1
  stream_transform: ^2.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/recenter_icon.svg